# NUMPY

##### getting started by importing pip install numpy

In [1]:
import numpy as np

### The Basics

In [2]:
a= np.array([1,2,3,6])     #1-d array
print(a)

[1 2 3 6]


In [3]:
b= np.array([[2,3,5],[50,90,43]])   #2-d array
print(b)

[[ 2  3  5]
 [50 90 43]]


In [4]:
c= np.array([[1.,2.,3.],[8.9,9.5,9.1],[0.0,0.0,0.0]])  #2-d array
c
#similarly you can get n-d arrays

array([[1. , 2. , 3. ],
       [8.9, 9.5, 9.1],
       [0. , 0. , 0. ]])

In [5]:
d= np.array([[[1,2,3],[4,5,6]],[[12,23,34],[89,90,78]]]) #3-d array
d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[12, 23, 34],
        [89, 90, 78]]])

In [6]:
#get Dimensions
a.ndim
c.ndim
d.ndim

3

In [7]:
#get shape of the array/configuration(no. of rows & column)of matrix
b.shape

(2, 3)

In [8]:
d.shape

(2, 2, 3)

In [9]:
#get datatype of array
d.dtype #default value int64

dtype('int64')

In [10]:
c.dtype #default value float64

dtype('float64')

In [11]:
#changing default dtype 
a= np.array([1,3,6,9], dtype='int16')
print(a.dtype)

int16


In [12]:
 #amount of memory occupied by a single element
 d.itemsize  #itemsize 8 for 64, 4 for 32, 2 for 16


8

In [13]:
#gives the total number of elements
a.size
d.size

12

In [14]:
#return the total memory occupied by all elements of array
d.nbytes  #itemsize*size

96

### Accessing specific elements, rows, columns, etc

In [15]:
arr= np.array([[1,2,3,4,5,6,7,8,9],[91,88,77,60,50,44,33,12,11]])
print(arr)

[[ 1  2  3  4  5  6  7  8  9]
 [91 88 77 60 50 44 33 12 11]]


In [16]:
#get specific element [r,c] :50
arr[1,4]


np.int64(50)

In [17]:
#get specific row
arr[1, :]

array([91, 88, 77, 60, 50, 44, 33, 12, 11])

In [18]:
#get specific column: 6,44
arr[ :,5]

array([ 6, 44])

In [19]:
#getting a little fancy[startindex: endidx: stepsize]
arr[0, 1:6:2] 
arr[0,1:-3:2] #negative indexing 


array([2, 4, 6])

### Changing  specific elements, rows, columns, etc

In [20]:
arr[0,5]=0 #changing specific element
print(arr)

[[ 1  2  3  4  5  0  7  8  9]
 [91 88 77 60 50 44 33 12 11]]


In [21]:
arr[: , 0]=[0,2]  #changing specific column
arr

array([[ 0,  2,  3,  4,  5,  0,  7,  8,  9],
       [ 2, 88, 77, 60, 50, 44, 33, 12, 11]])

##### 3D Array

In [22]:
arr2= np.array([[[0.9,0.7,0.5,0.3],[0.8,0.09,0.77,0.98]],[[0.21,1.2,2.2,3.5],[7.8,8.9,0.0,6.6]]])
print(arr2)
print(arr2.dtype)
print(arr2.size)
print(arr2.shape)

[[[0.9  0.7  0.5  0.3 ]
  [0.8  0.09 0.77 0.98]]

 [[0.21 1.2  2.2  3.5 ]
  [7.8  8.9  0.   6.6 ]]]
float64
16
(2, 2, 4)


In [23]:
arr2[0 , :, : ] #arr[k,i,j]

array([[0.9 , 0.7 , 0.5 , 0.3 ],
       [0.8 , 0.09, 0.77, 0.98]])

In [24]:
arr2[ : , 1, :]

array([[0.8 , 0.09, 0.77, 0.98],
       [7.8 , 8.9 , 0.  , 6.6 ]])

In [25]:
arr2[1, 1, 2]

np.float64(0.0)

In [26]:
#replace 
arr2[: , 1 ,:]= [[0.0,0.0,0.0,0.0],[1.1,1.1,1.1,1.1]]
arr2

array([[[0.9 , 0.7 , 0.5 , 0.3 ],
        [0.  , 0.  , 0.  , 0.  ]],

       [[0.21, 1.2 , 2.2 , 3.5 ],
        [1.1 , 1.1 , 1.1 , 1.1 ]]])

In [108]:
# you can index with a list in numpy
lst = np.array([1,5,7,8,90,66,4,3])
lst[[0,6,4]]

array([ 1,  4, 90])

### Initializing Different Types of Arrays
##### their default type = float

In [27]:
#all zeros matrix 
np.zeros((2,4))  #default 'float' type

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [28]:
#ones matrix
np.ones((3,4), dtype="int64")

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [29]:
# a matrix fully with a particular number
np.full((4,3), 99)

array([[99, 99, 99],
       [99, 99, 99],
       [99, 99, 99],
       [99, 99, 99]])

In [30]:
# a matrix with some similar shape as any other
#  matrix but have a particular number

np.full_like(arr , 8)

array([[8, 8, 8, 8, 8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8, 8, 8, 8, 8]])

In [31]:
np.random.rand(3, 3) #will give foating point numbers

array([[0.8002948 , 0.02655501, 0.96921022],
       [0.11876012, 0.83617257, 0.07889334],
       [0.50185555, 0.94466136, 0.05988194]])

In [32]:
np.random.random_sample(d.shape)

array([[[0.44335264, 0.36678264, 0.03237503],
        [0.09133623, 0.90304662, 0.42761427]],

       [[0.75701822, 0.06318393, 0.04681029],
        [0.99557485, 0.03228268, 0.15390778]]])

In [33]:
np.random.randint(8, size=(4,4)) 
#8 tells the nos. are within range 0 to 7 , 
# size tells size of matrix

array([[2, 7, 7, 3],
       [0, 4, 5, 4],
       [4, 7, 6, 3],
       [7, 7, 7, 3]], dtype=int32)

In [34]:
np.identity(3) 
#identity matrix is always a square matrix 
#so the parameter passed determines the number of ones.

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [35]:
# repeat same elements of array 
A = np.array([[23,45,67],[78,90,72]])
rep_A = np.repeat(A , 2, axis=0) 
rep_A

array([[23, 45, 67],
       [23, 45, 67],
       [78, 90, 72],
       [78, 90, 72]])

###### axis =0(column) , axis= 1(row)

In [36]:
rep2= np.repeat(arr , 3, axis=1)
rep2

array([[ 0,  0,  0,  2,  2,  2,  3,  3,  3,  4,  4,  4,  5,  5,  5,  0,
         0,  0,  7,  7,  7,  8,  8,  8,  9,  9,  9],
       [ 2,  2,  2, 88, 88, 88, 77, 77, 77, 60, 60, 60, 50, 50, 50, 44,
        44, 44, 33, 33, 33, 12, 12, 12, 11, 11, 11]])

## Question 1

In [37]:
arr1 = np.ones((5,5), dtype="int64")
arr2 = np.zeros((3,3), dtype="int64")
arr2[1,1]= 9
arr1[1:4 , 1:4] = arr2
print(arr1)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 9 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


####    Be careful when copying Arrays!!!!!

In [38]:
a= np.array([20,30,40,50])
b=  a.copy()
a[1]= 100
print(a)
print(b) 
#when we need two same arrays and
#  we need to make changes, but also want to keep
#the og array unchanged, we use 'copy()' function

[ 20 100  40  50]
[20 30 40 50]


## Mathematics

In [39]:
a= np.array([1,2,3,5,6,8])
print(a)

[1 2 3 5 6 8]


In [40]:
a+ 2
print(a)

[1 2 3 5 6 8]


In [41]:
a-3

array([-2, -1,  0,  2,  3,  5])

In [42]:
b = np.array([20,30,80,99,78,00])
a+b 

array([ 21,  32,  83, 104,  84,   8])

In [43]:
a * 2 

array([ 2,  4,  6, 10, 12, 16])

In [44]:
a/ 2

array([0.5, 1. , 1.5, 2.5, 3. , 4. ])

In [45]:
a**3

array([  1,   8,  27, 125, 216, 512])

In [46]:
#trignometric functions
np.cos(a)
np.sin(a)
np.tan(a)

array([ 1.55740772, -2.18503986, -0.14254654, -3.38051501, -0.29100619,
       -6.79971146])

## Linear Algebra

In [ ]:
#matrix multiplication 
#according to the rule of matrices, matrix multiplication will only
#occur when no. of column of 1st matches no. of rows of 2nd matrix
m1= np.random.randint(4, size=(3,2))
m2 = np.random.rand(2,3)
m3 = np.matmul(m1,m2)
print(m3)

[[0.         0.         0.        ]
 [3.29694682 2.98770807 2.69013588]
 [0.         0.         0.        ]]


In [59]:
#finding determinant
c = np.identity(3)
det = np.linalg.det(c)
print("determinant=", det)

determinant= 1.0


In [ ]:
#you can also find inverse,
#eigen values, eigen vectors using numpy

## Statistics

In [65]:
stats= np.array([[1,2,10,6],[7,9,8,4]])
stats

array([[ 1,  2, 10,  6],
       [ 7,  9,  8,  4]])

In [62]:
np.max(stats)

np.int64(9)

In [66]:
np.max(stats, axis=0)

array([ 7,  9, 10,  6])

In [68]:
np.min(stats, axis =1)

array([1, 4])

In [69]:
np.sum(stats)

np.int64(47)

In [71]:
np.sum(stats,axis=0)

array([ 8, 11, 18, 10])

## Reorganizing Arrays

In [75]:
before = np.array([[[3,4,5],[5,7,9]],[[2,3,0],[9,8,1]]])
print(before)
print("\n\n shape of an array is=",before.shape)

[[[3 4 5]
  [5 7 9]]

 [[2 3 0]
  [9 8 1]]]


 shape of an array is= (2, 2, 3)


In [80]:
after= before.reshape((6,2))
print(after)
after= before.reshape((4,3))
print("\n\n", after)
after= before.reshape((1,12))
print("\n\n", after)
after= before.reshape((6,1,2))
print("\n\n", after)

[[3 4]
 [5 5]
 [7 9]
 [2 3]
 [0 9]
 [8 1]]


 [[3 4 5]
 [5 7 9]
 [2 3 0]
 [9 8 1]]


 [[3 4 5 5 7 9 2 3 0 9 8 1]]


 [[[3 4]]

 [[5 5]]

 [[7 9]]

 [[2 3]]

 [[0 9]]

 [[8 1]]]


In [84]:
#Vertically stacking vectors
v1= np.array([1,2,3,4])
v2=np.array([8,7,9,0])

print(np.vstack([v1,v2]))

[[1 2 3 4]
 [8 7 9 0]]


In [86]:
np.vstack([v1,v2,v1,v2])

array([[1, 2, 3, 4],
       [8, 7, 9, 0],
       [1, 2, 3, 4],
       [8, 7, 9, 0]])

In [89]:
#horizontally stacking
h1= np.array([[2,90,80,60],[23,34,45,23]])
h2= np.array([[122,960,890,690],[230,304,405,20]])

print(np.hstack([h2,h1,h1]))

[[122 960 890 690   2  90  80  60   2  90  80  60]
 [230 304 405  20  23  34  45  23  23  34  45  23]]


## Load Data From File

In [95]:
file = np.genfromtxt("data.txt", delimiter = ",")
print(file)

[[  1.  13.  21.  11. 196.  75.   4.   3.  34.   6.   7.   8.   0.   1.
    2.   3.   4.   5.]
 [  3.  42.  12.  33. 766.  75.   4.  55.   6.   4.   3.   4.   5.   6.
    7.   0.  11.  12.]
 [  1.  22.  33.  11. 999.  11.   2.   1.  78.   0.   1.   2.   9.   8.
    7.   1.  76.  88.]]


In [97]:
file= file.astype('int32')
file

array([[  1,  13,  21,  11, 196,  75,   4,   3,  34,   6,   7,   8,   0,
          1,   2,   3,   4,   5],
       [  3,  42,  12,  33, 766,  75,   4,  55,   6,   4,   3,   4,   5,
          6,   7,   0,  11,  12],
       [  1,  22,  33,  11, 999,  11,   2,   1,  78,   0,   1,   2,   9,
          8,   7,   1,  76,  88]], dtype=int32)

In [ ]:
file>50 #checks for numbers greater than 50 and returns true

array([[False, False, False, False,  True,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [ ]:
file[file<50] #indexes less than 50 appears

array([ 1, 13, 21, 11,  4,  3, 34,  6,  7,  8,  0,  1,  2,  3,  4,  5,  3,
       42, 12, 33,  4,  6,  4,  3,  4,  5,  6,  7,  0, 11, 12,  1, 22, 33,
       11, 11,  2,  1,  0,  1,  2,  9,  8,  7,  1], dtype=int32)

In [ ]:
np.any(file >50, axis =0) 
#column wise checking if any data is greater than 50

array([False, False, False, False,  True,  True, False,  True,  True,
       False, False, False, False, False, False, False,  True,  True])

In [ ]:
(file >20 ) & (file<80)  
#return true for the numbers that are in range 20 to 80

array([[False, False,  True, False, False,  True, False, False,  True,
        False, False, False, False, False, False, False, False, False],
       [False,  True, False,  True, False,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False,  True,  True, False, False, False, False, False,  True,
        False, False, False, False, False, False, False,  True, False]])

# Question 2

In [114]:
test= np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20],[21,22,23,24,25],[26,27,28,29,30]])
print(test)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]]


In [116]:
test[2:4 ,0:2]


array([[11, 12],
       [16, 17]])

In [ ]:
test[[0,1,2,3],[1,2,3,4]] #using listing of indexes

array([ 2,  8, 14, 20])

In [121]:
test[[0,4,5], 3:]

array([[ 4,  5],
       [24, 25],
       [29, 30]])

##### peace :]